### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '\x08' when load ICVL dataset you provided in BaiduDisk

### ISSUE THREAD

**Issue by hsiaotung-tan** [bit-isp/HSIR#5]
The dataset you provided is arranged as follow
![Snipaste_2023-07-03_17-08-13](https://github.com/bit-isp/HSIR/assets/101790297/831b436a-eccf-47c3-aa8e-81df992c7a59)
![Snipaste_2023-07-03_17-07-55](https://github.com/bit-isp/HSIR/assets/101790297/63851e73-ef6b-4ff4-8445-6eaeb596411f)
 
but when run your script to retrain will raise this kind of error.

 `File "/htrainer. Trainng/Desktop/Project/HSIR/hsirun/train.py", line 78, in main
    if trainer.epoch < 30: trainer.train(train_loader1)
  File "/home/tanxiaodong/Desktop/Project/HSIR/hsir/trainer.py", line 175, in train
    for batch_idx, data in enumerate(train_loader):
  File "/home/tanxiaodong/miniconda3/envs/hsir/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/tanxiaodong/miniconda3/envs/hsir/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/tanxiaodong/miniconda3/envs/hsir/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/tanxiaodong/miniconda3/envs/hsir/lib/python3.10/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
_pickle.UnpicklingError: Caught UnpicklingError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/tanxiaodong/miniconda3/envs/hsir/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/tanxiaodong/miniconda3/envs/hsir/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/tanxiaodong/miniconda3/envs/hsir/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/tanxiaodong/Desktop/Project/HSIR/hsir/data/dataset.py", line 74, in __getitem__
    img = self.dataset[index]
  File "/home/tanxiaodong/Desktop/Project/HSIR/hsir/data/dataset.py", line 162, in __getitem__
    x = pickle.loads(raw_datum)
_pickle.UnpicklingError: invalid load key, '\x08'.`

**Comment by Zeqiang-Lai** [comment]
you could try to change backend to `caffe`

https://github.com/bit-isp/HSIR/blob/bea25d05efa8f8ac1195cb874190fce0d0e1333e/hsir/data/dataset.py#L137

I might upload the caffe version. I will check it and upload the pickle version as well later.
